apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
spec:
  project: default
  source:
    chart: gitlab
    repoURL: https://charts.gitlab.io/
    targetRevision: 7.11.0
    helm:
      values: |
        global:
          hosts:
            domain: example.com
          ingress:
            configureCertmanager: false
            tls:
              enabled: false
          externalTrafficPolicy: Cluster
        nginx-ingress:
          controller:
            service:
              type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated: {}
