apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
spec:
  project: default
  source:
    chart: keycloak
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.0.0
    helm:
      values: |
        service:
          type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated: {}
