apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  project: default
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2
    helm:
      values: |
        loki:
          service:
            type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated: {}