apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
spec:
  project: default
  source:
    chart: minio
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.8.0
    helm:
      values: |
        service:
          type: LoadBalancer
        mode: standalone
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated: {}
